name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build (latest_deps)
      run: cargo build --verbose
    - name: Run tests (latest_deps)
      run: cargo test --verbose

    - name: Build (wasm_compat)
      run: cargo build --verbose --no-default-features --features wasm_compat,std,bevy,rand,serde,hessian
    - name: Run tests (wasm_compat)
      run: cargo test --verbose --no-default-features --features wasm_compat,std,bevy,rand,serde,hessian
